export const ENDPOINT = {
    LOGIN: "auth/login",
    LOGOUT: "auth/logout",
    REFRESH: "auth/refresh",
    CMT: "cmt",
    COLOR: "color",
    FACTORY: "factory",
    INVENTORY: "inventory",
    MARKETPLACE: "marketplace",
    ONLINE_STORE: "onlinestore",
    PRODUCT_MODEL: "model",
    MODEL_COLOR: "model_color",
    MODEL_SIZE: "model_size",
    PRODUCT: "product",
    RACK: "rack",
    SIZE: "size",
    WAREHOUSE: "warehouse",
    USER: "user",
    ROLE: "role",
    REQUEST: "request",
    INBOUND: "inbound",
    MUTATION: "mutation",
    ORDER: "order"
}